# DB Connection Configuration

# 1. flyway + h2
# 클라우드 사용으로 인한 주석 처리

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/devdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  flyway:
#    baseline-version: 1
#    enabled: true
#    encoding: utf-8
#    baseline-on-migrate: true

# 2. NCP - cloud for mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-ajvuv.pub-cdb.ntruss.com:3306/foodrun_db
    username: mysql_dba
    password: foodrun2*

  # 3. message properties 불러오기 설정

  messages:
    basename: errors

# 4. MyBatis Config

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.flab.foodrun.domain.user
