# DB Connection Configuration

# flyway + h2
# 클라우드 사용으로 인한 주석 처리

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/devdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  flyway:
#    baseline-version: 1
#    enabled: true
#    encoding: utf-8
#    baseline-on-migrate: true

# NCP - cloud for mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}

  # 항상 SQL 데이터베이스를 초기화
  sql:
    init:
      mode: always

  # message properties 불러오기 설정

  messages:
    basename: errors

# MyBatis Config

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


# Naver Map API

naver:
  client:
    id: ${NAVER.ID}
    secret: ${NAVER.SECRET}
    url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode