# DB Connection Configuration

# 1. flyway + h2

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/devdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  flyway:
#    baseline-version: 1
#    enabled: true
#    encoding: utf-8
#    baseline-on-migrate: true

# 2. NCP - cloud for mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: db-ajvuv.pub-cdb.ntruss.com
    username: mysql_dba
    password: foodrun2*
