name: CI


on:
  push:
    branches:
      - main
      - 'feature/21'
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
    
      - name : Grant execute permission for gradlew
        run : chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.7.0
        with:
          badges-directory: badges
          generate-branches-badge: true
         
         
